// <auto-generated />
namespace WheelofAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Answer_Text : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Answer_Text));
        
        string IMigrationMetadata.Id
        {
            get { return "201911041027139_Answer_Text"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
