// <auto-generated />
namespace WheelofAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removed_answer_property : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_answer_property));
        
        string IMigrationMetadata.Id
        {
            get { return "201911041038209_removed_answer_property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
